CREATE TABLE IF NOT EXISTS `sclog_entries` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `logged_at_utc` DATETIME(6) NOT NULL,
    `level_name` VARCHAR(32) NOT NULL,
    `level_no` INT NOT NULL,
    `message` LONGTEXT NOT NULL,
    `logger_name` VARCHAR(255) NULL,
    `module` VARCHAR(255) NULL,
    `function_name` VARCHAR(255) NULL,
    `file_name` VARCHAR(255) NULL,
    `file_path` TEXT NULL,
    `line_no` INT NULL,
    `process_id` BIGINT NULL,
    `process_name` VARCHAR(255) NULL,
    `thread_id` BIGINT NULL,
    `thread_name` VARCHAR(255) NULL,
    `elapsed_ms` DOUBLE NOT NULL,
    `extra_json` JSON NULL,
    `exception_text` LONGTEXT NULL,
    `created_at_utc` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    INDEX `idx_sclog_entries_logged_at` (`logged_at_utc`),
    INDEX `idx_sclog_entries_level` (`level_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
